#+TITLE: Diff of Services

Diff of Services allows you to keep track of the changes to the Terms of Services, Privacy Policies, and other legal documents you may be subjected to reading throughout your time.
At this point in time, I cannot guarantee stability in the database format. At some time later I shall have migrations but not currently, so please don't use this as future changes /WILL/ require re-making the database and re-adding the documents.

* Reason
I dislike how long Terms of Services tend to be, but I deem it necessary for me to read them in their entirety. Unfortunately, the companies have a tendency to randomly change things, which becomes prohibitively expensive to re-read it each time there is a change, as it can often be minor. Thus I am creating this utility so that one can keep track of the changes and merely look over a diff of the changes between document version, to make it more feasible to read every version of the terms of service to which one agrees.

* Structure
This project will consist of a few crates (so yes in Rust) which will be developed in (approximately) the following order: a core api for managing things, a CLI to query or add documents, a Ratatui TUI to make easier viewing, a cross-platform Dioxus GUI, and finally a self-hostable server so one can sync between their various devices.

* Roadmap
Starting with CLI access until specified otherwise

- [X] Nix package for CLI
- [X] Create document
- [X] Be able to add new revisions to the document
  - [X] Keep track of date added and last date checked separately?
  - [X] Be able to move between revisions
  - [X] Ignore adding a revision if unchanged, instead updated last checked field
- [X] Generic diff
- [ ] Initial TUI work
  - [ ] Nix package for TUI
  - [ ] View documents, move between revision
  - [ ] Inline diff
  - [ ] Add documents (drag-and-drop vs copy-paste?)
- [ ] Initial GUI work (unless we just roll in with trolley and do a TUI-GUI)
  - [ ] Nix package for GUI
  - [ ] View documents, move between revisions
  - [ ] Inline diff
  - [ ] Add documents

At this point, this is the basic functionality for a single-device setup. We have a few options of directions to go after this
- [ ] Improved diffing
  - [ ] Paragraph added/removed diff
  - [ ] 2-way diff
  - [ ] Paragraph movement in diffs
  - [ ] If paragraph add-remove combo, do a sub-paragraph diff (word-by word, myers diff type idea)
- [ ] Nix module instead of just package
- [ ] Self-hosted sync server
  - [ ] Nix package and module (nixos vs hm?) for server
  - [ ] Central storage, client support remote connection
  - [ ] Clients keep local copy of latest revision of all (or maybe allow selection) docs + changes since last sync
  - [ ] Docker image
- [ ] Extract from HTML document
  - [ ] Check for update
  - [ ] Once server implemented, also support autoupdate
- [ ] If we're feeling ambitions, maybe even browser extension
  - [ ] On login / signup prompts (i.e. where "by click you agree to ... ") show if the stored revision is different that the linked one
  - [ ] One click add to document store (with HTML extraction)

* License
This project is licensed under the MIT license. You can do what you want with the code, just please attribute the original code to me.
